name: sero_te_amavi_rust_lint
description: Custom lint rules for sero_te_amavi_rust. Use match instead of fold for Option and Either. Configurable as warning or error in analysis_options.yaml.
version: 1.0.0
repository: https://github.com/lgmarchi/sero-te-amavi-rust
documentation: https://github.com/lgmarchi/sero-te-amavi-rust#readme
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  custom_lint_builder: ^0.8.0
